In [1]:
import numpy as np

In [5]:
np.arange(1.5, 10.5, 1.1)

array([ 1.5,  2.6,  3.7,  4.8,  5.9,  7. ,  8.1,  9.2, 10.3])

In [6]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [8]:
np.logspace(1, 10, 20, base=2)

array([   2.        ,    2.77730229,    3.85670399,    5.3556164 ,
          7.43708284,   10.32751358,   14.34131354,   19.91508143,
         27.65510059,   38.40328703,   53.32876841,   74.05505519,
        102.836637  ,  142.80421347,  198.30523421,  275.37679007,
        382.40229418,  531.02338276,  737.40622722, 1024.        ])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.zeros((3, 4, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
np.zeros((3, 4, 2, 3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [17]:
np.ones((3, 4, 2, 3))

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [18]:
arr = np.ones((3, 4))

In [19]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [21]:
arr * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [22]:
np.empty((3, 4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [24]:
arr1 = np.eye(5)

In [25]:
import pandas as pd

In [26]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [27]:
np.random.rand(2, 3)

array([[0.32591967, 0.21014533, 0.46521163],
       [0.12751209, 0.74364068, 0.81413185]])

In [28]:
np.random.randn(2, 3)

array([[ 0.64474816, -0.22491092, -1.64140994],
       [-0.99616863,  0.18405968,  1.00659544]])

In [30]:
arr2 = np.random.randint(1, 5, (3, 4))

In [31]:
arr2

array([[3, 2, 1, 4],
       [2, 1, 3, 3],
       [1, 4, 1, 3]])

In [33]:
arr2.shape

(3, 4)

In [34]:
arr2.reshape(6, 2)

array([[3, 2],
       [1, 4],
       [2, 1],
       [3, 3],
       [1, 4],
       [1, 3]])

In [35]:
arr2.reshape(2, 2, 3)

array([[[3, 2, 1],
        [4, 2, 1]],

       [[3, 3, 1],
        [4, 1, 3]]])

In [36]:
arr3 = np.random.randint(1, 10, (5, 6))

In [37]:
arr3

array([[1, 7, 3, 6, 3, 9],
       [8, 6, 8, 7, 8, 9],
       [6, 5, 7, 7, 8, 1],
       [8, 9, 9, 3, 7, 4],
       [6, 1, 5, 2, 9, 4]])

In [38]:
arr3 > 5

array([[False,  True, False,  True, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True, False],
       [ True,  True,  True, False,  True, False],
       [ True, False, False, False,  True, False]])

In [39]:
arr3[arr3 > 6]

array([7, 9, 8, 8, 7, 8, 9, 7, 7, 8, 8, 9, 9, 7, 9])

In [41]:
arr3[0, [0, 1]]

array([1, 7])

In [42]:
arr3[2:4, [2, 3]]

array([[7, 7],
       [9, 3]])

In [43]:
arr4 = np.random.randint(1, 5, (3, 3))
arr5 = np.random.randint(1, 8, (3, 3))

In [45]:
arr4

array([[1, 4, 4],
       [2, 2, 3],
       [4, 1, 1]])

In [46]:
arr5

array([[5, 6, 6],
       [6, 6, 1],
       [6, 2, 6]])

In [47]:
arr4 + arr5

array([[ 6, 10, 10],
       [ 8,  8,  4],
       [10,  3,  7]])

In [48]:
arr4 * arr5

array([[ 5, 24, 24],
       [12, 12,  3],
       [24,  2,  6]])

In [49]:
arr4 - arr5

array([[-4, -2, -2],
       [-4, -4,  2],
       [-2, -1, -5]])

In [50]:
arr4 @ arr5  # matrix multiplication

array([[53, 38, 34],
       [40, 30, 32],
       [32, 32, 31]])

In [51]:
arr4 / 0

C:\Users\ACER\AppData\Local\Temp\ipykernel_11748\3327478922.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [52]:
# numpy broadcasting

In [53]:
arr = np.zeros((3, 4))

In [54]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [56]:
a = np.array([1, 2, 3, 4])

In [59]:
a + arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [64]:
b = np.array([[3, 4, 5]])

In [66]:
b.ndim

2

In [68]:
arr + b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [73]:
arr6 = arr + b.T

In [74]:
b.T

array([[3],
       [4],
       [5]])

In [76]:
arr.T + b

array([[3., 4., 5.],
       [3., 4., 5.],
       [3., 4., 5.],
       [3., 4., 5.]])

In [75]:
arr6

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [77]:
np.sqrt(arr6)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [78]:
np.log10(arr6)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [79]:
np.exp(arr6)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [80]:
np.min(arr6)

3.0

In [81]:
np.max(arr6)

5.0