In [1]:
import numpy as np

In [2]:
# array manipulation

In [3]:
arr = np.random.randint(1, 10, (4, 4))

In [4]:
arr

array([[3, 5, 6, 1],
       [5, 7, 9, 1],
       [5, 4, 4, 7],
       [3, 7, 8, 7]])

In [5]:
arr.T

array([[3, 5, 5, 3],
       [5, 7, 4, 7],
       [6, 9, 4, 8],
       [1, 1, 7, 7]])

In [6]:
arr.flatten()

array([3, 5, 6, 1, 5, 7, 9, 1, 5, 4, 4, 7, 3, 7, 8, 7])

In [7]:
np.expand_dims(arr, axis=1)

array([[[3, 5, 6, 1]],

       [[5, 7, 9, 1]],

       [[5, 4, 4, 7]],

       [[3, 7, 8, 7]]])

In [8]:
data = np.array([[1], [2], [3]])

In [9]:
np.squeeze(data)

array([1, 2, 3])

In [10]:
np.repeat(data, 2)

array([1, 1, 2, 2, 3, 3])

In [11]:
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [12]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [16]:
# Binary Operation

In [13]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [14]:
arr1

array([[9, 5, 8, 2],
       [9, 2, 1, 5],
       [6, 5, 6, 2]])

In [15]:
arr2

array([[4, 8, 7, 8],
       [2, 3, 3, 2],
       [5, 7, 1, 8]])

In [17]:
arr1 + arr2

array([[13, 13, 15, 10],
       [11,  5,  4,  7],
       [11, 12,  7, 10]])

In [18]:
arr1 * arr2

array([[36, 40, 56, 16],
       [18,  6,  3, 10],
       [30, 35,  6, 16]])

In [19]:
arr1 - arr2

array([[ 5, -3,  1, -6],
       [ 7, -1, -2,  3],
       [ 1, -2,  5, -6]])

In [20]:
arr1 / arr2

array([[2.25      , 0.625     , 1.14285714, 0.25      ],
       [4.5       , 0.66666667, 0.33333333, 2.5       ],
       [1.2       , 0.71428571, 6.        , 0.25      ]])

In [22]:
arr1**arr2

array([[   6561,  390625, 2097152,     256],
       [     81,       8,       1,      25],
       [   7776,   78125,       6,     256]])

In [23]:
arr1

array([[9, 5, 8, 2],
       [9, 2, 1, 5],
       [6, 5, 6, 2]])

In [24]:
~arr1

array([[-10,  -6,  -9,  -3],
       [-10,  -3,  -2,  -6],
       [ -7,  -6,  -7,  -3]])

In [25]:
# String functions

In [26]:
arr = np.array(["sudh", "kumar"])

In [27]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [28]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [29]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [30]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [31]:
# Mathmatical functions

In [32]:
arr1

array([[9, 5, 8, 2],
       [9, 2, 1, 5],
       [6, 5, 6, 2]])

In [33]:
np.sin(arr1)

array([[ 0.41211849, -0.95892427,  0.98935825,  0.90929743],
       [ 0.41211849,  0.90929743,  0.84147098, -0.95892427],
       [-0.2794155 , -0.95892427, -0.2794155 ,  0.90929743]])

In [34]:
np.cos(arr1)

array([[-0.91113026,  0.28366219, -0.14550003, -0.41614684],
       [-0.91113026, -0.41614684,  0.54030231,  0.28366219],
       [ 0.96017029,  0.28366219,  0.96017029, -0.41614684]])

In [35]:
np.tan(arr1)

array([[-0.45231566, -3.38051501, -6.79971146, -2.18503986],
       [-0.45231566, -2.18503986,  1.55740772, -3.38051501],
       [-0.29100619, -3.38051501, -0.29100619, -2.18503986]])

In [36]:
np.power(arr1, 2)

array([[81, 25, 64,  4],
       [81,  4,  1, 25],
       [36, 25, 36,  4]], dtype=int32)

In [37]:
np.mean(arr1)

5.0

In [38]:
np.median(arr1)

5.0

In [39]:
np.std(arr1)

2.6770630673681683

In [40]:
np.var(arr1)

7.166666666666667

In [41]:
np.min(arr1)

1

In [42]:
np.max(arr1)

9

In [43]:
# numpy arithmatic operation

In [44]:
arr1 - arr2

array([[ 5, -3,  1, -6],
       [ 7, -1, -2,  3],
       [ 1, -2,  5, -6]])

In [45]:
np.subtract(arr1, arr2)

array([[ 5, -3,  1, -6],
       [ 7, -1, -2,  3],
       [ 1, -2,  5, -6]])

In [46]:
np.multiply(arr1, arr2)

array([[36, 40, 56, 16],
       [18,  6,  3, 10],
       [30, 35,  6, 16]])

In [47]:
np.mod(arr1, arr2)

array([[1, 5, 1, 2],
       [1, 2, 1, 1],
       [1, 5, 0, 2]])

In [48]:
np.sqrt(arr1)

array([[3.        , 2.23606798, 2.82842712, 1.41421356],
       [3.        , 1.41421356, 1.        , 2.23606798],
       [2.44948974, 2.23606798, 2.44948974, 1.41421356]])