In [1]:
import numpy as np

In [2]:
# sort, search and counting functions

In [5]:
arr = np.array([10, 3, 5, 16, 8, 100, 92])

In [6]:
arr

array([ 10,   3,   5,  16,   8, 100,  92])

In [7]:
np.sort(arr)

array([  3,   5,   8,  10,  16,  92, 100])

In [12]:
np.searchsorted(arr, 16)

3

In [13]:
arr1 = np.array([0, 232, 1, 1, 0, 0, 0, 44, 345, 12, 2, 10])

In [14]:
np.count_nonzero(arr1)

8

In [15]:
np.where(arr1 > 10)

(array([1, 7, 8, 9], dtype=int64),)

In [16]:
np.extract(arr1 > 5, arr1)

array([232,  44, 345,  12,  10])

In [17]:
# Byte swapping

In [18]:
arr1

array([  0, 232,   1,   1,   0,   0,   0,  44, 345,  12,   2,  10])

In [20]:
arr1.byteswap()

array([         0, -402653184,   16777216,   16777216,          0,
                0,          0,  738197504, 1493237760,  201326592,
         33554432,  167772160])

In [21]:
# copies and views

In [22]:
arr1

array([  0, 232,   1,   1,   0,   0,   0,  44, 345,  12,   2,  10])

In [35]:
a = np.copy(arr1)   # copy() is a deep copy. It will create a new object.

In [24]:
a

array([  0, 232,   1,   1,   0,   0,   0,  44, 345,  12,   2,  10])

In [36]:
b = arr1.view()  # view() is a swallow copy. Means it is not going to create a new object. It will point to the object like a reference varivale

In [31]:
b

array([  0, 232,   1,   1,   0,   0,   0,  44, 345,  12,   2,  10])

In [32]:
b[0] = 234

In [33]:
b

array([234, 232,   1,   1,   0,   0,   0,  44, 345,  12,   2,  10])

In [34]:
arr1

array([234, 232,   1,   1,   0,   0,   0,  44, 345,  12,   2,  10])

In [37]:
# Matrix Library

In [38]:
import numpy.matlib as nm

In [39]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [40]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [42]:
# Linear Algebra

In [44]:
arr2 = np.random.randint(1, 10, (3, 3))
arr3 = np.random.randint(1, 10, (3, 3))

In [45]:
arr2

array([[5, 9, 3],
       [6, 5, 2],
       [4, 5, 5]])

In [46]:
arr3

array([[9, 7, 2],
       [2, 4, 9],
       [2, 1, 6]])

In [47]:
np.dot(arr2, arr3)

array([[ 69,  74, 109],
       [ 68,  64,  69],
       [ 56,  53,  83]])

In [48]:
arr2 @ arr3

array([[ 69,  74, 109],
       [ 68,  64,  69],
       [ 56,  53,  83]])