In [1]:
import numpy as np

In [2]:
l = [1, 2, 3, 4, 5]

In [4]:
arr = np.array(l)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [8]:
arr1 = np.array([[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]
])

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
arr1.ndim

2

In [12]:
mat = np.matrix(l)

In [13]:
type(mat)

numpy.matrix

In [14]:
a = arr

In [15]:
a

array([1, 2, 3, 4, 5])

In [18]:
arr[0] = 100

In [19]:
arr

array([100, 100,   3,   4,   5])

In [20]:
a

array([100, 100,   3,   4,   5])

In [21]:
b = np.copy(arr)

In [22]:
b

array([100, 100,   3,   4,   5])

In [23]:
arr[2] = 10

In [24]:
arr

array([100, 100,  10,   4,   5])

In [25]:
b

array([100, 100,   3,   4,   5])

In [26]:
np.fromfunction(lambda i,j: i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
iterable = [i*i for i in range(5)]

In [30]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [31]:
np.fromstring("23 45 60", sep=" ")

array([23., 45., 60.])

In [32]:
arr

array([100, 100,  10,   4,   5])

In [33]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [34]:
arr.ndim

1

In [35]:
arr1.ndim

2

In [36]:
arr.size

5

In [37]:
arr1.size

9

In [38]:
arr.shape

(5,)

In [39]:
arr1.shape

(3, 3)

In [40]:
arr.dtype

dtype('int32')

In [41]:
arr1.dtype

dtype('int32')